# Generated by Django 3.0.5 on 2020-04-24 01:12

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200422_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('url', models.URLField(max_length=10, verbose_name='网址')),
                ('avatar', models.URLField(default='https://i.loli.net/2020/04/23/jGP8gQOYW75TSJp.png', verbose_name='头像')),
                ('desc', models.TextField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.URLField(default='https://i.loli.net/2020/04/23/lJLjEtbs2NFwynQ.jpg', verbose_name='文章封面'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_menu',
            field=models.BooleanField(default=False, verbose_name='添加到导航'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fas fa-home', max_length=30, verbose_name='导航图标'),
        ),
    ]
