# Generated by Django 3.0.5 on 2020-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200424_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='add_menu',
            field=models.BooleanField(default=False, verbose_name='添加到导航栏'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, verbose_name='网址'),
        ),
    ]
