# Generated by Django 3.0.5 on 2020-04-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bg_cover',
            field=models.URLField(default='http://119.23.243.154/image/Covteam-hack.jpg', max_length=100, verbose_name='背景图片'),
        ),
        migrations.AddField(
            model_name='site',
            name='desc',
            field=models.CharField(default='测试', max_length=50, verbose_name='网站描述'),
        ),
        migrations.AddField(
            model_name='site',
            name='dynamic_slogan',
            field=models.CharField(default='简简的我', max_length=50, verbose_name='动态标语'),
        ),
        migrations.AddField(
            model_name='site',
            name='icp_number',
            field=models.CharField(default='123', max_length=40, verbose_name='备案号'),
        ),
        migrations.AddField(
            model_name='site',
            name='icp_url',
            field=models.CharField(default='https:jwt1399.top', max_length=100, verbose_name='备案链接'),
        ),
        migrations.AddField(
            model_name='site',
            name='keywords',
            field=models.CharField(default='关键字测试', max_length=50, verbose_name='网站关键词'),
        ),
        migrations.AddField(
            model_name='site',
            name='slogan',
            field=models.CharField(default='简简', max_length=50, verbose_name='网站标语'),
        ),
    ]
