# Generated by Django 3.0.5 on 2020-04-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200426_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.URLField(default='https://jwt1399.top/favicon.png', max_length=100, verbose_name='网站logo'),
        ),
        migrations.AlterField(
            model_name='site',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='网站描述'),
        ),
        migrations.AlterField(
            model_name='site',
            name='dynamic_slogan',
            field=models.CharField(max_length=50, verbose_name='动态标语'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icp_number',
            field=models.CharField(max_length=40, verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icp_url',
            field=models.URLField(default='http://www.beian.miit.gov.cn/', max_length=100, verbose_name='备案链接'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slogan',
            field=models.CharField(max_length=50, verbose_name='网站标语'),
        ),
    ]
