# Generated by Django 3.0.5 on 2020-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200426_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='公告栏标题')),
                ('content', models.TextField(max_length=500, verbose_name='公告内容')),
            ],
            options={
                'verbose_name': '公告栏',
                'verbose_name_plural': '公告栏',
            },
        ),
        migrations.AddField(
            model_name='link',
            name='button_word',
            field=models.CharField(default='访问博客', max_length=10, verbose_name='跳转文字'),
        ),
    ]
