# Generated by Django 3.0.5 on 2020-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200426_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='icon',
            field=models.CharField(default='far fa-lightbulb', max_length=50, verbose_name='公告图标'),
        ),
    ]
