# Generated by Django 3.0.5 on 2020-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notice_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=100, verbose_name='appId')),
                ('appkey', models.CharField(max_length=100, verbose_name='appKey')),
                ('avatar', models.CharField(default='', max_length=100, verbose_name='头像展示方式')),
                ('pagesize', models.IntegerField(default='10', max_length=100, verbose_name='每页条数')),
                ('placeholder', models.CharField(max_length=100, verbose_name='评论框提示')),
            ],
        ),
    ]
