# Generated by Django 3.0.5 on 2020-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200426_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valine',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='avatar'),
        ),
    ]
