# Generated by Django 3.0.5 on 2020-04-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200426_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valine',
            options={'verbose_name': 'valine评论', 'verbose_name_plural': 'valine评论'},
        ),
    ]
