# Generated by Django 3.0.5 on 2020-04-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200426_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(verbose_name='头像')),
                ('career', models.CharField(max_length=50, verbose_name='从事')),
                ('introduction', models.TextField(verbose_name='介绍')),
                ('social_url', models.URLField(verbose_name='社交连接')),
                ('social_des', models.CharField(max_length=50, verbose_name='简介')),
                ('social_icon', models.CharField(default='fas fa-envelope-open', max_length=50, verbose_name='社交图标')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
