# Generated by Django 3.0.5 on 2020-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200427_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_url', models.URLField(verbose_name='社交链接')),
                ('social_desc', models.CharField(max_length=50, verbose_name='简介')),
                ('social_icon', models.CharField(default='fas fa-envelope-open', max_length=50, verbose_name='社交图标')),
            ],
            options={
                'verbose_name': '社交设置',
                'verbose_name_plural': '社交设置',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='social_des',
        ),
        migrations.RemoveField(
            model_name='about',
            name='social_icon',
        ),
        migrations.RemoveField(
            model_name='about',
            name='social_url',
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50, verbose_name='事业'),
        ),
        migrations.AlterField(
            model_name='valine',
            name='pagesize',
            field=models.IntegerField(default='10', verbose_name='pageSize'),
        ),
    ]
