# Generated by Django 3.0.5 on 2020-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200429_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='简文涛', max_length=10, verbose_name='作者'),
        ),
    ]
