# Generated by Django 3.0.5 on 2020-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200430_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=10, verbose_name='作者'),
        ),
    ]
