# Generated by Django 3.0.5 on 2020-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200430_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='简文涛', max_length=10, null=True, verbose_name='作者'),
        ),
    ]
